# Example of Queue deployment. The operator will receive this specification and will create a deployment of two "echo" pods.
apiVersion: example.com/v1
kind: Queue # Identifier of the resource type.
metadata:
  name: test-queue # Name of the "Queue" custom resource instance, may be changed to your liking
  namespace: default # Namespace must exist and account in KUBECONFIG must have sufficient permissions
spec:
  replicas: 2 # Number of "Queue" pods created.
