apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: queues.example.com
  namespace: default
spec:
  group: example.com
  names:
    kind: Queue
    plural: queues # If not specified, Kubernetes would assume the plural is "Echos"
    singular: queue
    shortNames:
      - queue
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec: # There is only one (required) field named "replicas" specifying how many pods are created by the Operator
              type: object
              properties:
                replicas:
                  type: integer
                  format: int32
              required: ["replicas"]